version: "3"

services:
  api:
    build:
      context: .
      target: dev
    environment:
      SQL_DATABASE: restaurant_db
      SQL_USERNAME: user
      SQL_PASSWORD: pass
      SQL_PORT: "5433"
      DB_HOST: db
    links:
    - "db:db"
    volumes:
      - ".:/srv"
    ports:  
      - "9000:9000"
    depends_on:
    - "db"
  db:
    image: postgres
    environment:                                                                                                                                                                                                                                                                                                                                      
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: restaurant_db
    ports:                      
      - "5433:5433"
    command: -p 5433
